name: Test, Migrate & Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Install NPM dependencies
        run: npm install
      - name: Build assets (Vite)
        run: npm run build
      - name: Copy .env
        run: cp .env.example .env
      - name: Générer la clé d'application
        run: php artisan key:generate
      - name: Run tests (SQLite en mémoire)
        run: php artisan test
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
      # - name: Run migrations (prod)
      #   run: php artisan migrate --force
      #   env:
      #     APP_KEY: ${{ secrets.APP_KEY }}
      #     APP_ENV: production
      #     DB_URL: ${{ secrets.DB_URL }}
      # - name: Trigger Vercel Deploy Hook
      #   run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
