name: Test, Migrate & Deploy to Vercel
on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP and Node
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip git curl nodejs npm libpq-dev
          docker-php-ext-install pdo pdo_pgsql || true
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build
      - name: Upload project artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-artifacts
          path: |
            vendor
            node_modules
            public/build

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Download project artifacts
        uses: actions/download-artifact@v4
        with:
          name: project-artifacts
      - name: Copy .env and generate app key
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
